### ISSUE TITLE
[0.4.2] [plugins] configure / bad substitution

### ISSUE THREAD

**Issue by Piraty** [Libvisual/libvisual#304]
running `configure` from https://github.com/Libvisual/libvisual/releases/download/libvisual-plugins-0.4.2/libvisual-plugins-0.4.2.tar.bz2
```
./configure: line 20765: $as_me:${as_lineno-$LINENO}: WARNING: *** GTK+ >= ${3.0} is not found.
	  	The libvisual GdkPixbuf image loader plugin won't be built.
		GdkPixbuf is included within gtk+-3.0 and newer, which can be
		downloaded at https://www.gtk.org/: bad substitution
=> ERROR: libvisual-plugins-0.4.2_1: do_configure: '${configure_script} ${configure_args}' exited with 1
=> ERROR:   in do_configure() at common/build-style/gnu-configure.sh:8
```

L20765
```
{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: *** GTK+ >= ${3.0} is not found.
```

https://github.com/Libvisual/libvisual/blob/013cd5fe7795989f045294af0c9f8fca430e6743/libvisual-plugins/configure.ac#L157

**Comment by hartwork** [comment]
Hi @Piraty I think we need to replace `${gtk_required_version}` by plain `gtk_required_version` there, m4 already filled the variable for us. Would you like to make a pull request against branch `0.4.x` or would you rather want me to do that?

PS: For anyone looking to get around it when there is no GTK+ 3.x present, please try `--disable-gdkpixbuf-plugin` in the meantime.

**Comment by Piraty** [comment]
there are more occurences of the subsitution bug.
please go ahead with this

**Comment by hartwork** [comment]
> there are more occurences of the subsitution bug.

@Piraty okay, will have a look.

> please go ahead with this

Okay, I will.

On an unrelated note, thanks for https://piraty.dev/txt/thunderbird-external-gnupg.html .

**Comment by hartwork** [comment]
@Piraty there is pull request #304 now. What do you think?
