### ISSUE TITLE
LV: Visualization lags when using PulseAudio

### ISSUE THREAD

**Issue by kaixiong** [Libvisual/libvisual#33]
The (incorrect) threading code in input_pulseaudio was recently removed in attempt to fix the weird issue where rendered frames appear to flip back and forth.

This reduced the implementation to a single blocking read with a single pa_simple_read() of 1024 samples (at 44,100Hz) followed by a frame render per main loop iteration and worked well on my test machine using PulseAudio 1.1 (Ubuntu 12.04 x64) but stutters horribly on PulseAudio 2.1 (tested on Ubuntu 12.10 x64). 

Although I haven't measured, I believed pa_simple_read() is taking longer to return than it needs to be, and is incredibly inconsistent timing wise despite reading the same amount of samples every frame. More investigation is needed. 

We will likely have to either restore threading code or use the complex API. Both approaches kind of suck.

EDIT: apparently this isn't limited to pulseaudio input.

**Comment by hartwork** [comment]
A quick note that I have reading from the microphone using the [Asynchronous API of PulseAudio](https://freedesktop.org/software/pulseaudio/doxygen/async.html) working at https://github.com/hartwork/audio_pump_demo . I could port that approach to libvisual `input_pulseaudio.c` as needed.

**Comment by hartwork** [comment]
There is pull request #149 now. Not that it's for `0.4.x` rather than `master`, `master` is planned to be next.
