### ISSUE TITLE
Oil/ORC link needs updating

### ISSUE THREAD

**Issue by hartwork** [Libvisual/libvisual#70]
Current/broken: http://code.entropywave.com/orc/
Proposal: http://gstreamer.freedesktop.org/projects/orc.html

Thanks :smiley:

**Comment by dsmit** [comment]
Without a new team, this project is halted ;(.

**Comment by hartwork** [comment]
@dsmit, that's too bad. It seems relevant to me. Do you have push access? Maybe fixing compilation and making an unstable but recent new release is all that's needed to attract some new people.

**Comment by kaixiong** [comment]
Closed by PR #192.
