### ISSUE TITLE
Restore Git tags for previous releases (help needed?)

### ISSUE THREAD

**Issue by hartwork** [Libvisual/libvisual#71]
Hi!

It looks like the history in Git covers releases back to 0.1.3 or more, yet there are not tags for releases in Git. Do you have them locally but forgot to push them? If not, it would be cool to have them restored properly. let me know, if you need help with that.

Best, Sebastian

**Comment by dsmit** [comment]
It looks as if we are without maintainers ;-)

Sorry.

**Comment by stuaxo** [comment]
@hartwork 

In translation - I guess, help is needed.   I guess it should be possible to work out where in the history the releases occured and add the tags ?

**Comment by hartwork** [comment]
Hi @stuaxo. Let's see what I can do.

**Comment by hartwork** [comment]
Hello again!

I had a closer look at both Subversion and Git history now. To restore the missing tags in Git, I would run these commands (in that order):
```
git tag libvisual-nebulus-0.1.3 5edffe9c87536c65e657b1e643f1d61da7b00c97
git tag libvisual-0.1.6 29a1e9f81e88d92ded7460eb2ea3a76e2991b237
git tag libvisual-xmms-0.1.6 29a1e9f81e88d92ded7460eb2ea3a76e2991b237
git tag libvisual-plugins-0.1.6 29a1e9f81e88d92ded7460eb2ea3a76e2991b237
git tag libvisual-gforce-0.1.0 4dc8efee6993b600444684abc2e3c7eaec8c8fe3
git tag libvisual-bmp-0.1.0 515ff0d8c20d83c219290bd5adec97ed6fba5beb
git tag libvisual-xmms-0.1.7 4deee8630d42b145e400e5ae9b9826540224756a
git tag libvisual-nebulus-0.1.4 93476ead0ebd36c7448a3fe83229a4c6f77ba90a
git tag libvisual-gforce-0.1.1 ed212b4338ee0f2b0c114bf6be08017742498d82
git tag libvisual-plugins-0.1.7 ed212b4338ee0f2b0c114bf6be08017742498d82
git tag libvisual-0.1.7 ae41ec95b148c1acf14f560a037fdb2a01820abc
git tag libvisual-0.2.0 ab8a7c2709dd291abbd48df14a4c41bb47f8000c
git tag libvisual-bmp-0.2.0 f6e4288030ab65a6c659b414a31966f4979770bf
git tag libvisual-plugins-0.2.0 f6e4288030ab65a6c659b414a31966f4979770bf
git tag libvisual-xmms-0.2.0 f6e4288030ab65a6c659b414a31966f4979770bf
```
For tags `libvisual-0.4.0` and `libvisual-plugins-0.4.0` there is no exact match in the Git history. My understanding is that that's because 0.4.0 was prepared on SVN branch `release_0_4_0` back then (forking off at Git commit 3a082e5125a2f3d2f158e2a6722d91d65f3ff2a5) and the history of that branch (8-9 commits more) has not been migrated to Git.

**Comment by hartwork** [comment]
I have restored the missing history of the 0.4.0 release branch (see the top 10 commits on https://github.com/hartwork/libvisual/commits/release-0.4.0).
Assuming your writable remote (to git@github.com:Libvisual/libvisual.git) is called `Libvisual`, this is what you could run to re-integrate the missing history (*after* creating all the tags above):
```
git remote add hartwork git@github.com:hartwork/libvisual.git
git push Libvisual hartwork/release-0.4.0:release-0.4.0

git tag libvisual-0.4.0 b6d27da428ede4454fa71e5cb6941413e1045b15
git tag libvisual-plugins-0.4.0 b6d27da428ede4454fa71e5cb6941413e1045b15
```
What do you think?

**Comment by stuaxo** [comment]
Looks good to me... maybe we can get you writable access if the other maintainers are busy...  am trying to track em down to ask for same..

**Comment by hartwork** [comment]
I just resent my mail of 2016-02-28 on push access to the three of them.

**Comment by stuaxo** [comment]
Cool, I tried for the two I could see addresse for on github.   Might be worth continuing on a separate fork if nothing happens (at least until they resurface)

**Comment by hartwork** [comment]
I was able to push the release tags and branch `release-0.4.0` now.

@stuaxo, I got your mail from a commit of yours and sent a mail to you now. If it doesn't arrive, please contact me for collaboration trough the address on my profile. Thanks!

Closing...
