### ISSUE TITLE
German translation (from Debian)

### ISSUE THREAD

**Issue by eribertomota** [Libvisual/libvisual#75]
Hi,

The attached patch provides German translation. The original patch is available in Debian bug 883826[1].

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883826

Thanks!

Eriberto

[110_add_de_translation.patch.zip](https://github.com/Libvisual/libvisual/files/2838874/110_add_de_translation.patch.zip)

**Comment by hartwork** [comment]
Hi Joao, thanks for taking this upstream.

For the record, the patch says

> This file is distributed under the same license as the libvisual-plugins package.

which seems to match this part

> Files: debian/*
> Copyright: 2005-2006 David Schleef <ds@schleef.org>
>            2006      Sebastian Dröge <slomo@ubuntu.com>
>            2007      Brandon Holtsclaw <brandon@imbrandon.com>
>            2007      Christopher James Halse Rogers <raof@ubuntu.com>
>            2007      David Leverton
>            2007      Martin Pitt <martin.pitt@ubuntu.com>
>            2007      Richard James Edmands <dmz@internode.on.net>
>            2011      Ana Beatriz Guerrero Lopez <ana@debian.org>
>            2011-2012 Steve Langasek <vorlon@debian.org>
>            2012      Michael Biebl <biebl@debian.org>
>            2015-2019 Joao Eriberto Mota Filho <eriberto@debian.org>
> License: GPL-2+

(due to path `debian/patches/110_add_de_translation.patch`) according to http://deb.debian.org/debian/pool/main/libv/libvisual-plugins/libvisual-plugins_0.4.0+dfsg1-13.debian.tar.xz .

**Comment by eribertomota** [comment]
Hi Sebastian,

Em seg, 18 de fev de 2019 às 09:38, Sebastian Pipping
<notifications@github.com> escreveu:
>
> Hi Joao, thanks for taking this upstream.
>
> For the record, the patch says
>
> This file is distributed under the same license as the libvisual-plugins package.
>
> which seems to match this part
>
> Files: debian/*
> Copyright: 2005-2006 David Schleef ds@schleef.org
> 2006 Sebastian Dröge slomo@ubuntu.com
> 2007 Brandon Holtsclaw brandon@imbrandon.com
> 2007 Christopher James Halse Rogers raof@ubuntu.com
> 2007 David Leverton
> 2007 Martin Pitt martin.pitt@ubuntu.com
> 2007 Richard James Edmands dmz@internode.on.net
> 2011 Ana Beatriz Guerrero Lopez ana@debian.org
> 2011-2012 Steve Langasek vorlon@debian.org
> 2012 Michael Biebl biebl@debian.org
> 2015-2019 Joao Eriberto Mota Filho eriberto@debian.org
> License: GPL-2+
>


This is the copyright notice for packaging. Please, follow the license
lines in patch:

+# Translation of libvisual-plugins to German
+# Copyright (C) 1999-2000 Christopher Wilson, 1999-2001 Zinx Verituse,
+#               2000-2001 Remi Arquier, 2000-2001 Richard Ashburn,
+#               2002-2006 Dennis Smit, 2004-2006 Antti Silvast,
+#               2005 yodor, Andrew Birck, Jean-Christophe Hoelt.
[...]
+"PO-Revision-Date: 2017-11-23 18:08:07+0200\n"
+"Last-Translator: Chris Leick <c.leick@vollbio.de>\n"

(add Chris Leick <c.leick@vollbio.de>, 2017)

with the same license for libvisual-plugins (GPL-2+).

Thanks in advance.

Regards,

Eriberto

**Comment by hartwork** [comment]
"same license as the libvisual-plugins package" and "Files: debian/*" seem to point to the same thing to me so no doubt about "GPL 2 or later" to me.

**Comment by eribertomota** [comment]
Em sex, 22 de fev de 2019 às 20:12, Sebastian Pipping <
notifications@github.com> escreveu:

> "same license as the libvisual-plugins package" and "Files: debian/*" seem
> to point to the same thing to me so no doubt about "GPL 2 or later" to me.
>
>
>
No. debian/* is the packaging system and its specific licensing. It can be
unlike the upstream license (must be compatible only). E.g.: you can have a
software using GPL-2+ and my packaging can use BSD-3-Clause. Please, see
the complete copyright file used in Debian here[1].

[1]
https://tracker.debian.org/media/packages/libv/libvisual-plugins/copyright-10.4.0dfsg1-13

Thanks

**Comment by hartwork** [comment]
I'm aware that packaging and upstream sources can have different licenses. What you say is in line rather than in contradiction with what I was saying.

**Comment by hartwork** [comment]
Fixed by pull request #141, merged to branch `0.4.x`, released as part of 0.4.1; closing as fixed.
