### ISSUE TITLE
[0.4.0] Compilation error on Windows 64 bits

### ISSUE THREAD

**Issue by vtorri** [Libvisual/libvisual#77]
on 32 bits, Eip register is used while Rip should be used on 64 bits

see https://github.com/Libvisual/libvisual/blob/master/libvisual/libvisual/lv_cpu.c#L136

**Comment by hartwork** [comment]
Please share compilation error output and the compiler in use. Thank you!

**Comment by vtorri** [comment]
libvisual 0.4.0 : mingw-w64 with MSYS2

./configure --host=x86_64-w64-mingw32 

btw, i tweak a bit configure because i also have this error : 

checking for the appropriate definition for size_t... configure: error: No type matching size_t in size

this is because on Windows 64 bits, the 'long' type is 32 bits, contrary to UNIX (see https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models)

**Comment by hartwork** [comment]
Thanks. Could you elaborate on the relationship to the eip/rip thing in the first message?

**Comment by vtorri** [comment]
no relationship, it's just 2 errors that forbid the compilation on windows with msys2+mingw-w64
